image:
  repository: dennishbb/airflow-prototype
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

airflow:
  executor: SequentialExecutor
  loadExamples: "False"

  admin:
    username: admin
    password: admin
    email: admin@example.com
    firstname: Admin
    lastname: User

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
