apiVersion: v1
kind: Secret
metadata:
  name: {{ include "airflow-prototype.fullname" . }}-secret
  labels:
    {{- include "airflow-prototype.labels" . | nindent 4 }}
type: Opaque
stringData:
  AIRFLOW__CORE__FERNET_KEY: {{ required "airflow.fernetKey is required" .Values.airflow.fernetKey | quote }}
  AIRFLOW__WEBSERVER__SECRET_KEY: "THIS_IS_NOT_SECURE_CHANGE_ME"
  _AIRFLOW_WWW_USER_USERNAME: {{ .Values.airflow.admin.username | quote }}
  _AIRFLOW_WWW_USER_PASSWORD: {{ .Values.airflow.admin.password | quote }}
  _AIRFLOW_WWW_USER_EMAIL: {{ .Values.airflow.admin.email | quote }}
  _AIRFLOW_WWW_USER_FIRSTNAME: {{ .Values.airflow.admin.firstname | quote }}
  _AIRFLOW_WWW_USER_LASTNAME: {{ .Values.airflow.admin.lastname | quote }}
