# E1 = dev / prototype environment

image:
  # Jenkins will build & push the image.
  # GitHub Actions will override `tag` at deploy time.
  pullPolicy: Always

service:
  type: ClusterIP

airflow:
  executor: SequentialExecutor
  loadExamples: "False"

resources:
  requests:
    cpu: "250m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

# E1 usually runs a single replica
replicaCount: 1

nodeSelector: {}
tolerations: []
affinity: {}
