# helm/values-e1.yaml
# E1 = dev / prototype environment

image:
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  nodePort: 31880

airflow:
  fernetKey: "jPTBIzMsb69Dmgcy_4MFFSE8QQ1UryCla7nMwExnuKY="
  executor: SequentialExecutor
  loadExamples: "False"

resources:
  requests:
    cpu: "500m"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

nodeSelector: {}
tolerations: []
affinity: {}
